config/routes.rb
Rails.application.routes.draw do
  resources :lps
  get 'home_page/show'
  root 'home_page#show'
  
  get '/artists/:id/records', to: 'artists#records', :as => :records_artist
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :lps



    validates :name, presence: true, uniqueness: true
    validates :description, presence: true, length: { maximum: 500 }
    
end

app/models/lp.rb
class Lp < ApplicationRecord
    belongs_to :artist



    validates :name, presence: true, uniqueness: true
    validates :description, presence: true, length: { maximum: 500 }
    validates :artist_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :records, :update, :destroy]

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @lps = Lp.all

    @aux_lps = []
    @lps.each do |lp|
      if lp.artist.name.downcase ==  @artist.name.downcase
        @aux_lps << lp
      end
    end
    @lps = @aux_lps
  end

  # GET /artists/1/lps
  def records
    @lps = Lp.all

    @aux_lps = []
    @lps.each do |lp|
      if lp.artist.name.downcase.include?  @artist.name.downcase
        @aux_lps << lp
      end
    end
    @lps = @aux_lps
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :description)
    end
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController
  def show
    @artists = Artist.all.length
    @lps = Lp.all.length
  end
end

app/controllers/lps_controller.rb
class LpsController < ApplicationController
  before_action :set_lp, only: [:show, :edit, :update, :destroy]

  # GET /lps
  # GET /lps.json
  def index
    @lps = Lp.all
    selected_artist = params[:search_artist_name]
    p selected_artist
    if selected_artist == ""
      @lps = Lp.all
    elsif selected_artist == nil
      @lps = Lp.all
    else
      @aux_lps = []
      @lps.each do |lp|
        if lp.artist.name.downcase.include?  selected_artist.downcase
          @aux_lps << lp
        end
      end
      @lps = @aux_lps
    end
  end

  # GET /lps/1
  # GET /lps/1.json
  def show
  end

  # GET /lps/new
  def new
    @lp = Lp.new
  end

  # GET /lps/1/edit
  def edit
  end

  # POST /lps
  # POST /lps.json
  def create
    @lp = Lp.new(lp_params)

    respond_to do |format|
      if @lp.save
        format.html { redirect_to @lp, notice: 'Lp was successfully created.' }
        format.json { render :show, status: :created, location: @lp }
      else
        format.html { render :new }
        format.json { render json: @lp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lps/1
  # PATCH/PUT /lps/1.json
  def update
    respond_to do |format|
      if @lp.update(lp_params)
        format.html { redirect_to @lp, notice: 'Lp was successfully updated.' }
        format.json { render :show, status: :ok, location: @lp }
      else
        format.html { render :edit }
        format.json { render json: @lp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lps/1
  # DELETE /lps/1.json
  def destroy
    @lp.destroy
    respond_to do |format|
      format.html { redirect_to lps_url, notice: 'Lp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lp
      @lp = Lp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lp_params
      params.require(:lp).permit(:name, :description, :artist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def active_class(link_path)
        current_page?(link_path) ? 'active' : ""
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/helpers/lps_helper.rb
module LpsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group row">
    <%= form.label :name, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :name, id: :artist_name, class: "form-control form-control-sm" %>
    </div>
  </div>

  <div class="field form-group row">
    <%= form.label :description, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_area :description, id: :artist_description, class: "form-control form-control-sm" %>
    </div>
  </div>

  <div class="field form-group row">
    <%= form.submit( class: "btn btn-large btn-primary") %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist, class: "btn btn-large btn-info" %> |
<%= link_to 'Back', artists_path, class: "btn btn-large btn-info" %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Artists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>LPs</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <% @plural_form = artist.lps.length == 1 ? 'LP' : 'LPs' %>
      <% @current_lps = artist.lps.length.to_s %>
      <% @joint_string = @current_lps +" "+ @plural_form %>
      <tr>
        <td class="name"><%= link_to artist.name, artist %></td>
        <td class="other"><%=  @joint_string %> </td>
        <td class="description"><%= artist.description %></td>
        
        <td><%= link_to 'Edit', edit_artist_path(artist), class: "btn btn-large btn-warning" %></td>
        <td><%= link_to 'Destroy', artist, class: "btn btn-large btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path, class: "btn btn-large btn-success" %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path, class: "btn btn-large btn-info" %>

app/views/artists/records.html.erb
<h1><%= @artist.name %>'s LPs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lps.each do |lp| %>
      <tr>
        <td class="name"><%= link_to lp.name, lp %></td>
        <td class="other"><%=  lp.artist.name %></td>
        <td class="description"><%= lp.description %></td> 
        <td><%= link_to 'Edit', edit_lp_path(lp), class: "btn btn-large btn-warning" %></td>
        <td><%= link_to 'Destroy', lp, class: "btn btn-large btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Back', @artist, class: "btn btn-large btn-info" %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Artist information</h1>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @artist.description %>
</p>

<p>
  <strong>Total of LPs:</strong>
  <%= @lps.length %>
</p>

<br>
<%= link_to 'List of LPs', records_artist_path(@artist), class: "btn btn-large btn-primary" %> |
<%= link_to 'Edit artist', edit_artist_path(@artist), class: "btn btn-large btn-warning" %> |
<%= link_to 'Back', artists_path, class: "btn btn-large btn-info" %>

app/views/home_page/show.html.erb
<div class="center hero-unit">
  <h1>Discography project Task</h1>

  <h2>
    This is the home page for the discography project task.
  </h2>

  <p> Hi fellow programmer, I'm <b>NICOLAU EJARQUE DEU</b> and this is my implementation of the task assigned to prove my Ruby On Rails skills. </p>
  <p> In this task you'll find two resources: <b>Artists</b> and <b>LPs</b>. </p>
  <p> You can manage them through the following links or visit their own pages to check all the records registered so far. </p>

  <h1>Artists:</h1> Currently we have <b><%= @artists%></b> artists registered. <br/>
  
  <%= link_to "Create artist entry", new_artist_path, class: "btn btn-large btn-success"%> <%= link_to "Check artist page", artists_path, class: "btn btn-large btn-primary"%>

  <h1>LPs:</h1> Currently we have <b><%= @lps%></b> LPs registered. <br/>
  
  <%= link_to "Create LP entry", new_lp_path, class: "btn btn-large btn-success"%> <%= link_to "Check LPs page", lps_path, class: "btn btn-large btn-primary"%>

  <br/>
  
  <div class="center info-text">
    You can check the Artist or LP details by clicking on it's name.<br/>
    You can also edit it's information, delete the entry or even adding new entries by clicking on the appropiate buttons on each page.
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discography CodiTramuntana</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <nav>
            <ul class="nav">
              <li class="nav-item <%=active_class(root_path)%>">     <%= link_to "Home", root_path  %></li>
              <li class="nav-item <%=active_class(artists_path)%>">  <%= link_to "Artist", artists_path %></li>
              <li class="nav-item <%=active_class(lps_path)%>">      <%= link_to "LP", lps_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/lps/_form.html.erb
<%= form_with(model: lp, local: true) do |form| %>
  <% if lp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lp.errors.count, "error") %> prohibited this lp from being saved:</h2>

      <ul>
      <% lp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  <div class="field form-group row">
    <%= form.label :name, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_field :name, id: :lp_name, class: "form-control form-control-sm" %>
    </div>
  </div>

  <div class="field form-group row">
    <%= form.label :description, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.text_area :description, id: :lp_description, class: "form-control form-control-sm" %>
    </div>
  </div>

  <div class="field form-group row">
    <%= form.label :artist_id, class: "col-sm-2 col-form-label col-form-label-sm" %>
    <div class="col-sm-10">
      <%= form.number_field :artist_id, id: :lp_artist_id, class: "form-control form-control-sm" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit( class: "btn btn-large btn-primary") %>
  </div>

<% end %>

app/views/lps/edit.html.erb
<h1>Editing Lp</h1>

<%= render 'form', lp: @lp %>

<%= link_to 'Show', @lp, class: "btn btn-large btn-info" %> |
<%= link_to 'Back', lps_path, class: "btn btn-large btn-info" %>

app/views/lps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lps</h1>
<div class="form-inline">
  <%= form_tag("/lps", method: "get") do %>
    <%= text_field_tag :search_artist_name, nil, placeholder: 'Artist name', class: "form-control" %>
    <%= submit_tag "Search", class: "btn btn-large btn-primary" %>
  <% end %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lps.each do |lp| %>
      <tr>
        <td class="name"><%= link_to lp.name, lp %></td>
        <td class="other"><%= link_to lp.artist.name, lp.artist %></td>
        <td class="description"><%= lp.description %></td> 
        <td><%= link_to 'Edit', edit_lp_path(lp), class: "btn btn-large btn-warning" %></td>
        <td><%= link_to 'Destroy', lp, class: "btn btn-large btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lp', new_lp_path, class: "btn btn-large btn-success" %>

app/views/lps/new.html.erb
<h1>New Lp</h1>

<%= render 'form', lp: @lp %>

<%= link_to 'Back', lps_path, class: "btn btn-large btn-info" %>

app/views/lps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @lp.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lp.description %>
</p>

<p>
  <strong>Artist:</strong>
  <%= link_to @lp.artist.name, @lp.artist %>
</p>

<%= link_to 'Edit', edit_lp_path(@lp), class: "btn btn-large btn-warning" %> |
<%= link_to 'Back', lps_path, class: "btn btn-large btn-info" %>